android.useAndroidX=true
android.newDsl=false
sdk.dir=/Users/aditya/Library/Android/sdk
org.gradle.java.home=C\:/Users/utham/.gradle/jdks/eclipse_adoptium-21-amd64-windows.2
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.paths=C\:/Users/utham/.gradle/jdks/eclipse_adoptium-21-amd64-windows.2
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=4
kotlin.daemon.jvmargs=-Xmx1536m


# Flow Neuroengine
FLOW_NEURO_BASE_URL=https://api.flowneuroengine.com
FLOW_NEURO_API_KEY=dummy_key
